### ISSUE TITLE
Parsing a .feature file fails only on windows -- "expected hacks"

### ISSUE THREAD

**Issue by Enrico2** [bbqsrc/gherkin-rust#14] opened 2020-08-25 22:39 UTC
Hi,

I could use some help figuring out this problem.
We have a few .feature files details simple test cases, instead of using cucumber, I'm using this crate directly so that I could implement the tests as a _unit test_, so that code coverage tools would give me a coverage report.

Here is the test code: https://github.com/apollographql/rust/blob/63c62f5a29c328e429d463b958a2bbb832b09b89/query-planner/src/lib.rs#L70-L114

This code only fails on windows. That `if cfg!(windows) {` line was an attempt to resolve the issue, but it didn't matter.
See this test run: https://github.com/apollographql/rust/runs/1028873036?check_suite_focus=true

You can navigate to other runs of the same branch as well.

The error message is unclear as well:
```
error at 6:12: expected hacks
```

The only place in this codebase that has the word "hacks" is [here](https://github.com/bbqsrc/gherkin-rust/blob/d640286e299b851d0c056a984371d4c983f6e8ac/src/parser.rs#L205), unfortunately, that's too deep in a macro for me to understand what it's supposed to mean.

I noticed that if I remove the `if cfg!(windows)` condition and always replace `\n` with `\r\n`, then I get the same error message on my mac.

Any help would be appreciated, thanks!

**Comment by bbqsrc** [comment] 2020-08-25 22:44
Heh, that "hacks" is never meant to appear in the output. But like everything that's not meant to appear, it ends up appearing. :smile:

It seems to be an issue with the handling for new lines, though I'm not sure why. You could try to changing the `nl0` rule to `( "\r\n" / "\n")` and see if that rectifies the issue.

**Comment by Enrico2** [comment] 2020-08-25 23:38
What do you mean by "the `nl0` rule" ?

**Comment by Enrico2** [comment] 2020-08-26 18:22
Can you be more specific? Thanks.

**Comment by bbqsrc** [comment] 2020-08-26 18:23
https://github.com/bbqsrc/gherkin-rust/blob/master/src/parser.rs#L181

**Comment by Enrico2** [comment] 2020-08-26 18:48
I'm not on a windows machine (this was failing in CI on windows) so it'd have been too much effort to iterate on this on the gherkin repo, submit a patch, etc.

I solved this on my end by literally replacing `\r\n` with `\n` after reading the file (I was not aware that Windows' reading of a UTF8 string takes the same byte value of newline (`0x0A`) into `\r\n`)

Thanks for the pointer though! would you like me to keep this issue open for your own tracking purposes to fix at some point, or should I close?

**Comment by bbqsrc** [comment] 2020-08-26 18:49
Yeah I'll keep it around, thanks. :)

**Comment by bbqsrc** [comment] 2020-09-08 12:34
I haven't been able to reproduce this issue. If someone can provide a link to a file that demonstrates this behaviour, it would be appreciated.

**Comment by Enrico2** [comment] 2020-09-08 17:30
File: https://github.com/apollographql/federation/blob/main/query-planner/tests/features/basic/aliases.feature

Try this in a test:
```
let path = .. wherever that file is ..;
let feature = read_to_string(&path).unwrap();
let feature = Feature::parse(feature).unwrap(); // this should fail on windows
```

Try this github action:
```
name: Test on Windows

on:
  pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      ### INSTALL RUST ###
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: stable
		  target: x86_64-pc-windows-msvc
          profile: minimal
          override: true

      ### RUN TESTS ###
      - name: Test (cargo test)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--workspace --locked -- --nocapture"
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
```

Alternatively, you can reproduce in our own repository, that might be easier:
1. Fork https://github.com/apollographql/federation
2. [Remove this `if` condition](https://github.com/apollographql/federation/blob/114a998e3135b261c74f19137e9efb6f27529435/query-planner/src/lib.rs#L96-L100) (that's the workaround).
3. Put up a PR to trigger the github action

**Comment by bbqsrc** [comment] 2020-09-08 17:32
Oh hey, thanks! I'll take a look. :smile:

**Comment by bbqsrc** [comment] 2020-09-08 17:47
Yup, @Enrico2, ran your code locally. Did `git clone`, edited out that if block, it still passes.

Perhaps you could run `cargo update` and see if it's now fixed for you as well?

**Comment by Enrico2** [comment] 2020-09-08 19:19
Are you on windows? Yeah I'll try with 0.8.1 but I'm on a mac, so I can only reproduce this on a Github action.

OK! Looks like it doesn't happen with the recent version: https://github.com/apollographql/federation/pull/137/checks?check_run_id=1087661734

It'd be cool to find which commit on your end fixed the issue.

**Comment by bbqsrc** [comment] 2020-09-08 19:24
It was fixed in this commit: https://github.com/bbqsrc/gherkin-rust/commit/8949d1dff6eb657fefbf39a2c5e8c72e05c64448

This, however, wasn't in any release until 0.8.1 it seems. In any case, it's there now. :smile:

**Closed by bbqsrc** 2020-09-08 19:24 UTC

**Comment by Enrico2** [comment] 2020-09-08 19:40
🙏
